### ISSUE TITLE
community.general.bitwarden from your ee is not incuded

### ISSUE THREAD

**Issue by gsg-git** [GiuffreLab/building-execution-environments#1]
Hello again!
Ive b een using your ee all the time, but the bitwarden one failes for me:
`Enter passphrase for /runner/artifacts/8285/ssh_key_data: 
Identity added: /runner/artifacts/8285/ssh_key_data (/runner/artifacts/8285/ssh_key_data)
No config file found; using defaults

PLAY [Retrieve Bitwarden password test] ****************************************

TASK [Get 'password' from Bitwarden record 'madtest'] **************************
fatal: [www43]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'community.general.bitwarden'. Error was a <class 'FileNotFoundError'>, original message: [Errno 2] No such file or directory: 'bw'. [Errno 2] No such file or directory: 'bw'"}

PLAY RECAP *********************************************************************
www43                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
`
the playbook:
`---
- name: Retrieve Bitwarden password test
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Get 'password' from Bitwarden record 'madtest'
      ansible.builtin.debug:
        msg: >-
          {{ lookup('community.general.bitwarden', 'madtest', field='password') }}
`
![grafik](https://github.com/user-attachments/assets/8235c49a-d1b4-444e-be03-8bcd7e570850)
Thank you!

**Comment by GiuffreLab** [comment]
To make this easier to read, I've cleaned up your playbook example

```yaml
---
- name: Retrieve Bitwarden password test
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Get 'password' from Bitwarden record 'madtest'
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.bitwarden', 'madtest', field='password') }}"
```

A few notes about your playbook.

```yaml
hosts: all
```

This line means you are running this against all hosts in the `bitwarden` inventory file, is this where your bit warden information is? Or is it on the ansible control node (`AWX`)?

```yaml
become: true
```

This means you are running this as `root` on the `bitwarden` hosts. Is it setup as the `root` user, or is it setup as a specific user? Make sure `root` has the access it needs (you can test locally on the machine) or else you need to remove this and use the appropriate user to access the `bitwarden` vault
